# Generated by Django 3.0.2 on 2020-03-04 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł filmu')),
                ('nomination_category', models.IntegerField(choices=[(1, 'Best Picture'), (2, 'Cinematography'), (3, 'Costume design'), (4, 'Film editing'), (5, 'International feature film'), (6, 'Makeup and hairstyling'), (7, 'Music'), (8, 'Visual effect'), (9, 'Adapted screenplay'), (10, 'Original screenplay'), (11, 'No movie category')], verbose_name='Kategorie filmu')),
                ('winner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nominowana osoba')),
                ('nomination_category', models.IntegerField(choices=[(1, 'Actor in a leading role'), (2, 'Actress in a leading role'), (3, 'Actor in a supporting role'), (4, 'Actress in a supporting role'), (5, 'Directing')], verbose_name='Kategoria osoby')),
                ('winner', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominations.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ManyToManyField(related_name='movies_set', to='nominations.Movie')),
                ('people', models.ManyToManyField(related_name='people_set', to='nominations.Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
