# Generated by Django 3.0.2 on 2020-07-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0004_auto_20200528_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='nominations/media/profile_images/default_avatar.JPG', upload_to=''),
        ),
    ]
