# Generated by Django 3.0.2 on 2020-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0005_auto_20200718_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default_avatar.JPG', upload_to=''),
        ),
    ]
